ClusterName=simcluster
SlurmctldHost=linux1
SlurmUser=root

AuthType=auth/none
CredType=cred/none
MpiDefault=none
ProctrackType=proctrack/pgid
ReturnToService=2
SwitchType=switch/none
TaskPlugin=task/affinity

SlurmctldPort=6817
SlurmdPort=6818
SlurmctldPidFile=/run/slurm/slurmctld.pid
SlurmdPidFile=/run/slurm/slurmd.pid
StateSaveLocation=/opt/slurm-sim/var/spool/slurmctld
SlurmdSpoolDir=/opt/slurm-sim/var/spool/slurmd
PluginDir=/opt/slurm-sim/lib/slurm

InactiveLimit=0
KillWait=30
MinJobAge=30
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU
PriorityType=priority/basic

AccountingStorageType=accounting_storage/none
JobAcctGatherType=jobacct_gather/none
JobCompType=jobcomp/none

SlurmctldDebug=debug
SlurmdDebug=debug
SlurmctldLogFile=/opt/slurm-sim/etc/slurmctld.log
SlurmSchedLogFile=/opt/slurm-sim/etc/sched.log
SlurmSchedLogLevel=1

NodeName=linux1 CPUs=4 RealMemory=2000 State=UNKNOWN
PartitionName=debug Nodes=linux1 Default=YES MaxTime=INFINITE State=UP

