ClusterName=stanage-smoke
SchedulerType=sched/backfill
SelectType=select/cons_tres
NodeName=node[001-004] CPUs=64 RealMemory=257024 State=UNKNOWN
PartitionName=standard Nodes=node[001-004] Default=YES MaxTime=96:00:00 State=UP
