TimeStart=0
TimeStop=1
SecondsBeforeFirstJob=1
ClockScaling=3000
SharedMemoryName=/slurm_sim_stanage.shm
EventsFile=sim.events.realistic
TimeAfterAllEventsDone=2
FirstJobDelay=0
CompJobDelay=0
TimeLimitDelay=0
